/**
 * Static index of every playable OST track the mini-player can browse
 * (Phase 7 mini-player expansion): HGSS (the album the app already fetches
 * curated tracks from) plus one album per mainline generation. Generated by
 * `tools/build-music-catalog.cjs` from khinsider's game-soundtracks album
 * pages -- see that script's header for curation rules. Audio itself is
 * never bundled or committed; `src/main/musicCache.ts` fetches-and-caches a
 * track's bytes on first play using this index's stored track-page URL.
 */
import raw from './musicCatalog.json';

export type MusicGen =
  | 'gen1'
  | 'gen2'
  | 'gen3'
  | 'gen4'
  | 'hgss'
  | 'gen5'
  | 'gen6'
  | 'gen7'
  | 'gen8'
  | 'gen9';

export interface CatalogTrack {
  /** Stable id. The app's 9 pre-existing curated HGSS tracks (ambient
   *  rotation, battle, evolution ceremony) keep their original symbolic ids
   *  (route29, battleWild, ...) so old on-disk caches and the battle/ceremony
   *  code that names them directly keep working; every other track is
   *  `${gen}-${NNN}` (NNN = 1-based row position on that gen's album page). */
  id: string;
  title: string;
  /** khinsider track-page URL (relative to downloads.khinsider.com), scraped
   *  verbatim from the album page and never re-encoded -- see
   *  musicCache.ts's header comment on khinsider's double-encoded hrefs. */
  url: string;
  gen: MusicGen;
  /** True for the handful of curated ids that are themselves short jingles
   *  (currently just evolutionFanfare, HGSS's 5s ceremony fanfare) --
   *  excluded from the mini-player's browsable list but still resolvable via
   *  ensureMusicTrack for the ceremony code that plays them directly. */
  jingle: boolean;
}

export const MUSIC_CATALOG: readonly CatalogTrack[] = raw as CatalogTrack[];

export const MUSIC_CATALOG_BY_ID: ReadonlyMap<string, CatalogTrack> = new Map(
  MUSIC_CATALOG.map((t) => [t.id, t])
);

/** Tracks worth showing in the mini-player's searchable list/auto-cycle pool
 *  -- everything except forced-in jingles (see `jingle` above). */
export const BROWSABLE_TRACK_IDS: readonly string[] = MUSIC_CATALOG.filter((t) => !t.jingle).map(
  (t) => t.id
);

/** Display order and label for the mini-player's generation filter. */
export const GEN_ORDER: readonly MusicGen[] = [
  'gen1',
  'gen2',
  'gen3',
  'gen4',
  'hgss',
  'gen5',
  'gen6',
  'gen7',
  'gen8',
  'gen9'
];

export const GEN_LABELS: Record<MusicGen, string> = {
  gen1: 'Gen 1 — R/G/B/Y',
  gen2: 'Gen 2 — G/S/C',
  gen3: 'Gen 3 — R/S/E',
  gen4: 'Gen 4 — D/P/Pt',
  hgss: 'Gen 4 — HGSS',
  gen5: 'Gen 5 — B/W',
  gen6: 'Gen 6 — X/Y',
  gen7: 'Gen 7 — S/M',
  gen8: 'Gen 8 — Sw/Sh',
  gen9: 'Gen 9 — Sc/Vi'
};
