/**
 * OST tracks, fetched at runtime from khinsider and cached to userData
 * (Phase 7, expanded to the full mini-player catalog) — mirrors
 * `spriteCache.ts`'s pattern: main owns the network and disk actors the
 * renderer's CSP forbids; the renderer just gets bytes.
 *
 * khinsider serves no direct download link — getting an mp3 is a two-hop
 * scrape, verified live against the real site: `MUSIC_CATALOG` (generated by
 * `tools/build-music-catalog.cjs`) stores each track's khinsider track-PAGE
 * URL directly (scraped verbatim, never re-encoded — its query string is
 * already double URL-encoded by khinsider itself, e.g. `%2520` for a literal
 * `%20`); fetching that page's HTML and reading its `<audio src="...">` tag
 * gives the real, direct mp3 URL. That URL's host varies per album (seen:
 * `nu.`, `jetta.`, and no subdomain at all — never assume one), which is why
 * the `<audio>` tag is matched rather than a fixed hostname.
 *
 * A catalog id is the only thing ever taken from the renderer, and it's
 * checked against `MUSIC_CATALOG_BY_ID` before it ever reaches a filesystem
 * path or URL — an unknown id is treated as "not found", not looked up on
 * disk.
 *
 * Only one track fetch (interactive "play this now", or a background
 * catalog-warm — see `requestTrack`/`prefetchTrack`) runs at a time,
 * process-wide: a new interactive request cancels whatever's in flight (an
 * interactive need always wins); a prefetch request no-ops if anything else
 * is already in flight rather than preempting it. Prefetch bytes are piped
 * straight to disk and never held in memory or returned to the renderer.
 */
import { app } from 'electron';
import { createWriteStream, existsSync } from 'node:fs';
import { mkdir, readFile, readdir, rename, stat, unlink, utimes, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';
import type { ReadableStream as NodeWebReadableStream } from 'node:stream/web';
import { MUSIC_CATALOG_BY_ID } from '../shared/musicCatalog';

// Sent on every request out of caution — untested whether khinsider actually
// rejects a request with no browser-like User-Agent, since live verification
// always sent one from the first request onward.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const FETCH_TIMEOUT_MS = 15_000;

/** Disk cache cap. A full generation's album is ~600-800MB, so this needs
 *  headroom for "one gen plus change," not just the original 9-track curated
 *  set. LRU by access time (see `enforceCacheCap`), evicted only as needed. */
export const CACHE_CAP_BYTES = 1024 * 1024 * 1024; // 1GB
/** Background prefetch stops (rather than evicting to make room) once the
 *  cache is within this many bytes of the cap — interactive "play this now"
 *  fetches always still evict as needed; only the background warm backs off. */
export const CACHE_HEADROOM_BYTES = 50 * 1024 * 1024; // 50MB

function cacheDir(): string {
  return join(app.getPath('userData'), 'audio', 'music');
}

function cachePath(id: string): string {
  return join(cacheDir(), `${id}.mp3`);
}

async function fetchWithTimeout(
  url: string,
  opts: RequestInit = {},
  timeoutMs = FETCH_TIMEOUT_MS
): Promise<Response | null> {
  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      ...opts,
      signal: controller.signal,
      headers: { 'User-Agent': UA, ...opts.headers }
    });
    return res.ok ? res : null;
  } catch {
    return null;
  } finally {
    clearTimeout(t);
  }
}

/** The real, direct mp3 URL embedded in a track's page — read off the
 *  page's `<audio src="...">` tag rather than a fixed CDN hostname (see file
 *  header: the subdomain isn't consistent across albums). */
async function findDirectMp3Url(trackPageHref: string): Promise<string | null> {
  const res = await fetchWithTimeout(`https://downloads.khinsider.com${trackPageHref}`);
  if (!res) return null;
  const html = await res.text();
  const m = html.match(/<audio[^>]*\bsrc="([^"]+\.mp3)"/i);
  return m ? m[1] : null;
}

/** Deletes oldest-by-mtime cached files until the cache dir is back under
 *  `CACHE_CAP_BYTES`. Cache hits touch mtime (see `touchCacheFile`), so this
 *  is access-order LRU, not write-order. */
async function enforceCacheCap(): Promise<void> {
  const dir = cacheDir();
  let names: string[];
  try {
    names = await readdir(dir);
  } catch {
    return;
  }
  const entries = await Promise.all(
    names.map(async (name) => {
      try {
        const s = await stat(join(dir, name));
        return { name, size: s.size, mtimeMs: s.mtimeMs };
      } catch {
        return null;
      }
    })
  );
  const files = entries.filter((e): e is { name: string; size: number; mtimeMs: number } => e !== null);
  let total = files.reduce((sum, f) => sum + f.size, 0);
  if (total <= CACHE_CAP_BYTES) return;

  files.sort((a, b) => a.mtimeMs - b.mtimeMs);
  for (const f of files) {
    if (total <= CACHE_CAP_BYTES) break;
    try {
      await unlink(join(dir, f.name));
      total -= f.size;
    } catch {
      // Ignore — a concurrent read/rename losing the race is harmless here.
    }
  }
}

async function touchCacheFile(id: string): Promise<void> {
  try {
    const now = new Date();
    await utimes(cachePath(id), now, now);
  } catch {
    // Best-effort — a failed touch just makes this file look older than it
    // is for LRU purposes, not a correctness problem.
  }
}

/** Total bytes currently on disk in the music cache, and the cap they're
 *  measured against — exposed to the renderer's background-warm scheduler so
 *  it can stop trickling before eviction would otherwise kick in. */
export async function getCacheStatus(): Promise<{ bytes: number; cap: number; headroom: number }> {
  const dir = cacheDir();
  let names: string[];
  try {
    names = await readdir(dir);
  } catch {
    return { bytes: 0, cap: CACHE_CAP_BYTES, headroom: CACHE_HEADROOM_BYTES };
  }
  const sizes = await Promise.all(
    names.map(async (name) => {
      try {
        return (await stat(join(dir, name))).size;
      } catch {
        return 0;
      }
    })
  );
  return {
    bytes: sizes.reduce((a, b) => a + b, 0),
    cap: CACHE_CAP_BYTES,
    headroom: CACHE_HEADROOM_BYTES
  };
}

/** Bytes for a previously-cached track, or null if not yet fetched. Touches
 *  the file's mtime on a hit (LRU access-order). */
export async function getCachedTrack(id: string): Promise<ArrayBuffer | null> {
  const p = cachePath(id);
  if (!existsSync(p)) return null;
  try {
    const buf = await readFile(p);
    void touchCacheFile(id);
    return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
  } catch {
    return null;
  }
}

// --- single-flight fetch coordination --------------------------------------
// At most one track download runs at a time, process-wide (renderer memory
// safety + politeness to khinsider — see file header). An interactive
// "play this now" request always cancels whatever's in flight (including a
// background prefetch); a prefetch request no-ops if anything is already in
// flight rather than preempting it — the caller's trickle loop just retries
// later.
let inFlightId: string | null = null;
let inFlightKind: 'interactive' | 'prefetch' | null = null;
let inFlightController: AbortController | null = null;

function cancelInFlight(): void {
  inFlightController?.abort();
  inFlightId = null;
  inFlightKind = null;
  inFlightController = null;
}

/** Cached bytes if present; otherwise the khinsider fetch, cached to disk
 *  before returning. Null on any failure (offline, unknown id, a layout
 *  change upstream, or being cancelled by a newer interactive request) — the
 *  caller (audioEngine) treats that as "skip this track" rather than a
 *  crash. Used for tracks about to actually play, so bytes are buffered in
 *  memory and handed back over IPC (Howler needs them) — unlike
 *  `prefetchTrack`, which never does this. */
export async function ensureMusicTrack(id: string): Promise<ArrayBuffer | null> {
  const cached = await getCachedTrack(id);
  if (cached) return cached;

  const track = MUSIC_CATALOG_BY_ID.get(id);
  if (!track) return null;

  cancelInFlight();
  const controller = new AbortController();
  inFlightId = id;
  inFlightKind = 'interactive';
  inFlightController = controller;
  try {
    const mp3Url = await findDirectMp3Url(track.url);
    if (!mp3Url || controller.signal.aborted) return null;
    const res = await fetchWithTimeout(mp3Url, { signal: controller.signal });
    if (!res || controller.signal.aborted) return null;

    const bytes = await res.arrayBuffer();
    await mkdir(cacheDir(), { recursive: true });
    await writeFile(cachePath(id), Buffer.from(bytes));
    void enforceCacheCap();
    return bytes;
  } catch {
    return null;
  } finally {
    if (inFlightId === id) {
      inFlightId = null;
      inFlightKind = null;
      inFlightController = null;
    }
  }
}

/** Background catalog-warm: fetches `id` straight to disk (streamed, never
 *  buffered in memory, never returned to the renderer) if not already
 *  cached. No-ops (returns `'busy'`) if another fetch is already in flight —
 *  the renderer's trickle loop is expected to retry later rather than this
 *  function queuing anything itself, keeping "one download in flight,
 *  process-wide" simple to reason about. Returns `'cached'` if the track was
 *  already on disk (still touches its mtime), `'ok'` on a successful fetch,
 *  or `'failed'` on any error / unknown id / abort. */
export async function prefetchTrack(id: string): Promise<'cached' | 'ok' | 'busy' | 'failed'> {
  if (existsSync(cachePath(id))) {
    void touchCacheFile(id);
    return 'cached';
  }
  if (inFlightId) return 'busy';

  const track = MUSIC_CATALOG_BY_ID.get(id);
  if (!track) return 'failed';

  const controller = new AbortController();
  inFlightId = id;
  inFlightKind = 'prefetch';
  inFlightController = controller;
  const tmpPath = `${cachePath(id)}.part`;
  try {
    const mp3Url = await findDirectMp3Url(track.url);
    if (!mp3Url || controller.signal.aborted) return 'failed';
    const res = await fetchWithTimeout(mp3Url, { signal: controller.signal });
    if (!res || !res.body || controller.signal.aborted) return 'failed';

    await mkdir(cacheDir(), { recursive: true });
    await pipeline(
      Readable.fromWeb(res.body as unknown as NodeWebReadableStream<Uint8Array>),
      createWriteStream(tmpPath)
    );
    if (controller.signal.aborted) throw new Error('aborted mid-write');
    await rename(tmpPath, cachePath(id));
    void enforceCacheCap();
    return 'ok';
  } catch {
    try {
      await unlink(tmpPath);
    } catch {
      // No partial file to clean up — fine.
    }
    return 'failed';
  } finally {
    if (inFlightId === id) {
      inFlightId = null;
      inFlightKind = null;
      inFlightController = null;
    }
  }
}

/** Stops the background prefetch currently in flight, if any (e.g. the user
 *  switched generation filters, or turned music off) — never cancels an
 *  interactive `ensureMusicTrack` fetch, which already always wins over
 *  prefetch (see `ensureMusicTrack`'s own `cancelInFlight` call). */
export function cancelPrefetch(): void {
  if (inFlightKind === 'prefetch') cancelInFlight();
}
